version: "3.8"

services:

  tpnode:
    image: ghcr.io/vd2org/tpnode:${VERSION:-latest}
    deploy:
      mode: global
      update_config:
        order: stop-first
      rollback_config:
        order: stop-first
    container_name: tpnode
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - /:/rootfs
    restart: always
    environment:
      - HOST_ROOT=/opt/tpnode
      - INIT_AUTH_SERVER=${INIT_AUTH_SERVER:-}
      - INIT_TOKEN=${INIT_TOKEN:-}
