name: PUBLISH

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        id: build
        env:
          GITHUB_TOKEN: ${{ matrix.platform.app }}
        run: |
          export APP_VERSION=$(cat APP_VERSION)

          export VERSION=$(echo ${{ github.ref }} | cut -d / -f 3)
          export VERSION_CUT=$(echo $VERSION | cut -d _ -f 2 -f 1)

          if [ "$VERSION_CUT" == "$VERSION" ]; then
            echo "Version of the app($APP_VERSION) and the version of the image($VERSION) are mismatched!"
            exit 1
          fi

          export IMAGE=ghcr.io/${{ github.repository }}:$VERSION
          export PLATFORMS=linux/amd64,linux/arm64

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

          docker buildx create --name local-build
          docker buildx use local-build

          docker buildx b --platform $PLATFORMS --build-arg APP_VERSION=$APP_VERSION -t $IMAGE --push .
