name: TEST

on:
  push:
    branches:
      - 'master'
  pull_request:
    ~

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        id: build
        env:
          GITHUB_TOKEN: ${{ matrix.platform.app }}
        run: |
          export APP_VERSION=$(cat APP_VERSION)

          export IMAGE=ghcr.io/${{ github.repository }}:test
          export PLATFORMS=linux/amd64,linux/arm64

          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

          docker buildx create --name local-build
          docker buildx use local-build

          docker buildx b --platform $PLATFORMS --build-arg APP_VERSION=$APP_VERSION -t $IMAGE .
